// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzmeuyvricmshgwoohrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6bWV1eXZyaWNtc2hnd29vaHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzMyNjcsImV4cCI6MjA2NDcwOTI2N30.wx__LYoAgazofTssH7Yms_zK4oPEeQlW7bewEj-2JOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);